version: "3"

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper-server:
    container_name: zookeeper-server
    image: bitnami/zookeeper:latest
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka-server:
    image: bitnami/kafka:latest
    container_name: kafka-server
    ports:
      - '29092:29092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-server:9092,EXTERNAL://localhost:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper-server
    networks:
      - kafka-net
      
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka-server:9092
    depends_on: 
      - kafka-server
    networks:
      - kafka-net
      
  postgress:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./Database/accounts.sql:/docker-entrypoint-initdb.d/2-accounts.sql
      - ./Database/custom.sql:/docker-entrypoint-initdb.d/3-custom.sql
    networks:
      - kafka-net
    environment:
      POSTGRES_USER: tech
      POSTGRES_PASSWORD: test
      POSTGRES_DB: payments
      
  api-producer:
    build: ./ApiAndProducer
    ports:
      - 9001:8080
    networks:
      - kafka-net
    volumes:
      - ./ApiAndProducer/bin:/app/
    command:
      [
        "./wait-for-it.sh",
        "postgress:5432",
        "kafka-server:9092",
        "-t",
        "100",
        "--",
        "java",
        "-jar",
        "app.jar",
      ]
    depends_on:
      - postgress
      - kafka-server
